application: barbara-mac

version: 1
runtime: python27
api_version: 1
default_expiration: "1d" # expiration time for static content

builtins:
- deferred: on
- appstats: on
- threadsafe: yes

includes:
- handlers.yaml

